### ISSUE TITLE
Error codes

### ISSUE THREAD

**Issue by jaydubal** [cognidox/OfficeToPDF#10]
The error codes received, no longer match the list shown in documentation.
Can you please update the list? I got error codes like 35, 65 ...

**Comment by vittala** [comment]
Hi 
Error codes are ORed together if multiple errors occur, so:

35 = 1 (failure) + 2 (unknown error) + 32 (unsupported file format)
65 = 1 (failure) + 64 (source file not found)

Regards
Vittal
