### ISSUE TITLE
Problem starting from TFS Network service

### ISSUE THREAD

**Issue by AdriedB** [cognidox/OfficeToPDF#12]
Hi,

When I tried to use OfficeToPDF within a TFS batch proces (runs under Network Service), then I get the following error.

**Retrieving the COM class factory for component with CLSID {000209FF-0000-0000-C000-000000000046} failed due to the following error: 80080005 Server execution failed (Exception from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).**

I already gave the Network Service alle the right in the DCOM Config (Component Services/DCOM Config/Microsft Wordt 97 - 2003-document)

Any help is appreciated!

Kind regards,

Adrie

**Comment by vittala** [comment]
Hi Adrie

When you gave DCOM permissions, you should provide rights to the Word application, rather than Word document.

Did you follow the steps suggested in https://blogs.technet.microsoft.com/the_microsoft_excel_support_team_blog/2012/11/12/microsoft-excel-or-microsoft-word-does-not-appear-in-dcom-configuration-snap-in/

Regards
Vittal

**Comment by vittala** [comment]
Also, in the DCOM permissions for "Microsoft Word 97 - 2003-document", ensure that the NETWORK SERVICE has all "Launch and Activation Permissions"

**Comment by AdriedB** [comment]
Hi Vittal,

Thanks for your quick response.

On my system (W7/Office 2016) I had to set the privileges for "Microsoft Word 97 - 2003-document". 

Then I got the following error:

_The remote procedure call failed. (Exception from HRESULT: 0x800706BE)
Unhandled Exception: System.Runtime.InteropServices.COMException: The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
   at Microsoft.Office.Interop.Word.ApplicationClass.Quit(Object& SaveChanges, Object& OriginalFormat, Object& RouteDocument)
   at OfficeToPDF.WordConverter.Convert(String inputFile, String outputFile, Hashtable options)
   at OfficeToPDF.Program.Main(String[] args)_

but this error disappeared after creating the desktop folder  as you suggested previously. 
	C:\Windows\SysWOW64\config\systemprofile\Desktop 

Unfortunately now I ran into another error message:

_Retrieving the COM class factory for component with CLSID {000209FF-0000-0000-C000-000000000046} failed due to the following error: 80080005 Server execution failed (Exception from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).
Did not convert_

Do you have any suggestions left?

Kind regard,
Adrie

**Comment by vittala** [comment]
Hi Adrie

Have you tried giving the user that TFS runs as (rather than just NETWORK SERVICE) full DCOM permissions (Launch & Activation / Access & Configuration Permissions)?

I'd also do a repair on your Office installation to ensure that's not the source of the problem.

Regards
Vittal

**Comment by AdriedB** [comment]
Hi Vittal,

I switched from Network Servive to a user account to start the TFS Agent.
I also added this user to the DCOM security,
I repaired the installation of Office 2016.

OfficeToPdf is working with this user account locally.

But running within the TFS Agent I get another error message:

          _Object reference not set to an instance of an object._

And with the task manager I can see that Winword.exe is running and claiming more and more memory, 1.402.260K and still  counting. Something is still going wrong.

Kind regards,
Adrie

**Comment by vittala** [comment]
Hi Adrie

Difficult to say what's causing this as we can't replicate your environment here and can't see your documents.

I don't know what you're trying to make OfficeToPDF do, but sometimes in a server context it's best to avoid Office altogether (Microsoft specifically state that running Office in a server context isn't supported). What we've seen some success with (depending on the style of the documents being converted) is to use LibreOffice and it's convert-to switch. e.g.

"c:\Program Files (x86)\LibreOffice 5\program\soffice.exe" --headless --convert-to pdf "some-doc.docx"

You may find this route easier than battling Microsoft!

Regards
Vittal

**Comment by AdriedB** [comment]
Hi Vittal,

You're right. This cost to much time to get it working.

I'll give LibreOffice a try, but our experience before was that the layout changed after opening a document with OpenOffice.

But I'will try it with LibreOffice, maybe it works for our documents.

Thanks again for your quick response!

Kind regards,
Adrie

**Comment by AdriedB** [comment]
Hi Chris,

Thanks for you additional information. I haven't succeeded in getting MS
Office to work in combination with the TFS service.

I do not want to work with a user account for the TFS service.

So for this moment  I don't have a solution for the automatic doc/docx
conversion in combination with TFS.

Kind regards,
Adrie
