### ISSUE TITLE
RPC server unavailable

### ISSUE THREAD

**Issue by yania0** [cognidox/OfficeToPDF#13]
hi, I use OfficeToPDF

and I found this error :
RPC server unavailable (HRESULT: 0x800706BA)
location : Microsoft.Office.Interop.Word.ApplicationClass.Quit(Object& SaveChanges, Object& OriginalFormat, Object& RouteDocument)

OS : windows 8.1
Office : MS Office 2013

This error seems to occur when I try to convert a MS Word file to pdf.

Any help?
thanks.

**Comment by vittala** [comment]
Are you running OfficeToPDF directly or as a service (e.g. through a web server)?

Create the folder  C:\Windows\SysWOW64\config\systemprofile\Desktop and see if this helps.

Regards
Vittal

**Comment by yania0** [comment]
I used OfficeToPDF directly on my computer as a command line, not service.
I ran the program on the path you taught, but the results were the same as before.

**Comment by vittala** [comment]
Does this happen if you are converting multiple documents, one after the other?
Have you tried using the /noquit switch for officetopdf?
Have you performed a repair of your Office installation?

**Comment by vittala** [comment]
Try this build https://github.com/cognidox/OfficeToPDF/releases/tag/v1.8.7.0

**Comment by yania0** [comment]
hi, It works done well. thank you!

**Comment by vittala** [comment]
OK - thanks for the update
