### ISSUE TITLE
Did not convert

### ISSUE THREAD

**Issue by jaleman1082** [cognidox/OfficeToPDF#14]
Los márgenes derecho e izquierdo, el espacio entre columnas o las sangrías de párrafo son demasiado largos para el ancho de la página en algunas secciones.
Did not convert

I didn't convert the attach file, when I try save as PDF with Word it's OK, but fails with OfficeToPDF.
[28.docx](https://github.com/cognidox/OfficeToPDF/files/1617051/28.docx)

Thanks a lot, in advance.

**Comment by vittala** [comment]
Hi

See if this release resolves the issue: https://github.com/cognidox/OfficeToPDF/releases/tag/v1.8.6.0 

Regards
Vittal

**Comment by jaleman1082** [comment]
Hello, 

Thank you very much for the quick response.
Could you share me the nightly build.

Regards
Julio Alemán

**Comment by vittala** [comment]
Hi - download the latest build from https://github.com/cognidox/OfficeToPDF/releases/tag/v1.8.7.0

**Comment by jaleman1082** [comment]
Hi - This build solves my problem, thank you very much. 

Very nice work.
