### ISSUE TITLE
Concurrent mode

### ISSUE THREAD

**Issue by viirtus** [cognidox/OfficeToPDF#21]
Hi.
It is possible to use OfficeToPDF in concurrent mode?  _probably no_
Now, if I try to run more than 1 instance it will instantly fail with popup for saving untitled document. Also, until I manually kill WINWORD.exe each next run fall with `RPC_E_CALL_REJECTED`.

Working in one thread took to long time.

**Comment by vittala** [comment]
Hi

Unfortunately no. Office is not designed to be run concurrently (see https://support.microsoft.com/en-gb/help/257757/considerations-for-server-side-automation-of-office for the details) and because OfficeToPDF relies on Office, we can't support concurrent conversions.

Regards
Vittal
