### ISSUE TITLE
Error HRESULT E_FAIL has been returned from a call to a COM component

### ISSUE THREAD

**Issue by mikeyww** [cognidox/OfficeToPDF#23]
Seems to have broken after a Windows update.

**Comment by mikeyww** [comment]
Sorry I did not provide enough information. It worked when I tried it
again. Perhaps rebooting helped.

Switches: /bookmarks /hidden /readonly

Files: DOCX to PDF

I don't think there were dialog boxes. I did not try with other file 
types. I'm not sure which Windows updates were applied (but the most 
recent ones in the past week or so)!

Microsoft Word 2016 MSO (16.0.9126.2109) 64-bit

Computer: TOSHIBA PORTEGE R930
Operating system: Microsoft Windows 7 Professional 64-bit Version 6.1.7601
Service pack: 1.0
Total physical memory (MB): 16262
Available physical memory (MB): 11296
Processor: Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz 64-bit
Processor type: Intel64 Family 6 Model 58 Stepping 9
BIOS: TOSHIBA Default System BIOS Version 6.80  
Motherboard: TOSHIBA PORTEGE R930 Version A0
Display name: Intel(R) HD Graphics 4000
Display resolution: 1366 x 768
Display dots per inch (DPI): 120

Mike

________________________________

**Comment by vittala** [comment]
Hi Mike

Thanks for the update.

There's nothing inherent in the latest updates that would stop things working, so I'd say it was probably a Word.exe process hanging around causing the problems. The reboot would have started you off with a clean slate and resolved things.

Regards
Vittal
