### ISSUE TITLE
The converted pdf file has one line on the page top for word files (.doc)

### ISSUE THREAD

**Issue by Pana** [cognidox/OfficeToPDF#26]
![20180518110914](https://user-images.githubusercontent.com/552081/40214191-f424655c-5a8b-11e8-85f9-18feb069bc57.png)

My officetopdf version is 1.8

**Comment by vittala** [comment]
Hi

Do you see this with this pre-release https://github.com/cognidox/OfficeToPDF/releases/tag/1.8.14.0

If you do, could you attach an example document so we can test.

Regards
Vittal

**Comment by Pana** [comment]
The 1.8.14 version seems works for me, i will test it for a while.
Thanks
