### ISSUE TITLE
OfficeToPDF doesn't work when there's no available printer 

### ISSUE THREAD

**Issue by luiscla27** [cognidox/OfficeToPDF#28]
OfficeToPDF is returning the message "Did not convert" when there's no available printer.

Steps to reproduce:
1. The test enviroment must not have any printer installed.
2. Try to convert any Excel file (i only tested excel) by using the command line: OfficeToPDF /verbose "test.xlsx" "test.pdf"
3. The error message is shown.

**Comment by luiscla27** [comment]
The expected behavior is that the file converts to PDF or either shows a more detailed message like "Theres no printer available"

**Comment by vittala** [comment]
Hi 

Could you confirm the version of Office that you're using.

Regards
Vittal

**Comment by luiscla27** [comment]
Of course vittala,

Im using MSO 365 ProPlus - es-es v16.0.9126.2259 (Office 2016)

**Comment by vittala** [comment]
Hi - Try this build https://github.com/cognidox/OfficeToPDF/releases/tag/v1.8.21.0 which will return an error if there are no printers

**Comment by luiscla27** [comment]
it works! thank you,

**Comment by vittala** [comment]
No problems!
