### ISSUE TITLE
Protect PDF against printing

### ISSUE THREAD

**Issue by bottasergio** [cognidox/OfficeToPDF#34]
I want to to protect the generated PDF against printig. I use this syntax:

OfficeToPDF.exe "WORD CON IMAGEN.docx" xx.pdf /pdf_restrict_print /pdf_owner_pass "pass7"

But, when I open xx.pdf I can print it without entering the password.

**Comment by vittala** [comment]
Hi 

There's a bug caused by command line parsing. Try putting the filename of the document that needs converting and the destination file at the end of the command:

OfficeToPDF.exe  /pdf_restrict_print /pdf_owner_pass "pass7" "WORD CON IMAGEN.docx" xx.pdf

Regards
Vittal

**Comment by bottasergio** [comment]
Excellent! It works!!!!
