### ISSUE TITLE
Release version, ROADMAP?

### ISSUE THREAD

**Issue by luiscla27** [cognidox/OfficeToPDF#40]
Hello!

Are you going to add a [release] version soon? 
It has been  more than a year since you released version 1.8,

Currently you only have [pre-release] versions of OfficeToPDF,
![image](https://user-images.githubusercontent.com/29953012/53644045-37c50680-3bfb-11e9-9a46-5a6b10626bdb.png)
Best,

**Comment by vittala** [comment]
Hi

The latest pre-release is stable - we have been swamped in our day jobs, so a formal release is taking it's time.

Regards
Vittal

**Comment by vittala** [comment]
Hi 

We've just released version 1.9 with the latest update.

Regards
Vittal
