### ISSUE TITLE
x86 compatibility

### ISSUE THREAD

**Issue by ElvisFlewOffToMars** [cognidox/OfficeToPDF#47]
Hello.
I try to use OfficeToPDF tool in Linux (CentOS 7). And use wine for it. 
But OfficeToPDF is x86_64 and I've got x86 compatibility problem.
Have you x86 tool version?

Thank you.

**Comment by vittala** [comment]
Hi 

OfficeToPDF is 32bit (e.g. see the latest pre-release https://github.com/cognidox/OfficeToPDF/releases/tag/v1.8.22.0). We've never tried running under Wine, so we can't say whether it'd work correctly in that environment.

Regards
Vittal
