### ISSUE TITLE
How about Multithreading?

### ISSUE THREAD

**Issue by Sascha4j** [cognidox/OfficeToPDF#49]
should it be possible to call the exe in a multithreaded environment? for example a server process which does batch converting

**Comment by vittala** [comment]
Hi

It may be possible but you should be aware that you may get blocking and problems if Office dialogs are present and you're trying to convert multiple Office documents of the same type (e.g. xlsx) at the same time.

You may want to read:
https://docs.microsoft.com/en-us/visualstudio/vsto/threading-support-in-office?view=vs-2019

Regards
Vittal
