### ISSUE TITLE
In Word, header underlines and some borders are not rendered

### ISSUE THREAD

**Issue by vittala** [cognidox/OfficeToPDF#55]
Looks like there's a but with Word interop where if ScreenUpdating is set to false on the Word object, not everything is rendered.

The solution is to turn on ScreenUpdating just before rendering the PDF

**Comment by Zombaya** [comment]
Are you planning on releasing a build version with this fix included in the near future?

We are experiencing some issues which seem to be related to this and I would like to try if this would fix the issues we are having.

**Comment by vittala** [comment]
We've just put up release 1.9 which includes these fixes
