### ISSUE TITLE
Sometimes the word will popup an alert window how to close it, and not influence later converter

### ISSUE THREAD

**Issue by Pana** [cognidox/OfficeToPDF#6]
FYI

**Comment by Pana** [comment]
When convert an file sometimes will popup an dialog, how do i close it so it won't cause later convert faile

**Comment by kkman2016** [comment]
It occurred  to me too.
some unexpected "file save" dialog, "file recovery" confirm dialog etc, it makes some of the coming converting failed. 

Please do me a favor.  
Very appreciate!

**Comment by Pana** [comment]
@vittala Any solutions ?

**Comment by Pana** [comment]
I have add an logic, if the convert failed manual kill WINWORD.exe, this can ensure the process keep going
