### ISSUE TITLE
Cannot convert when using as windows service

### ISSUE THREAD

**Issue by zssng** [cognidox/OfficeToPDF#66]
I got this error when i call office to pdf in windows service.
```
C:/xx/OfficeToPDF.exe C:/xx/office_to_pdf/dist/live/ODa0EN1Gq-a.xlsx
stdout: ���� COM �๤���� CLSID Ϊ {00024500-0000-0000-C000-000000000046} �����ʧ�ܣ�ԭ���ǳ������´���: 80070520 ָ���ĵ�¼�Ự�����ڡ������ѱ���ֹ�� (�쳣���� HRESULT:0x80070520)��
Did not convert
```
Does the OfficeToPDF support calling in service?

**Comment by polybas** [comment]
I think that the problem is in the user under which the service is running. By default, this is Local System. Try to change the user under which you log into the system.

**Comment by zssng** [comment]
Thank you for your reply. I retried changing service account, get this `failed due to the following error: 80070520 A specified logon session does not exist. It may already have been terminated. (Exception from HRESULT: 0x80070520).` I check the event log ,Audit was success.

**Comment by zssng** [comment]
Using built-in admin account as service account,got this  `stdout: ���� COM �๤���� CLSID Ϊ {00024500-0000-0000-C000-000000000046} �����ʧ�ܣ�ԭ���ǳ������´���: 80070005 �ܾ����ʡ� (�쳣���� HRESULT:0x80070005 (E_ACCESSDENIED))��
Did not convert`

**Comment by polybas** [comment]
Is xlsx converted from console command (not service)?

**Comment by zssng** [comment]
I package a node app as exe,the exe run as service, use `const {exec} = require('child_process')` to call `officetopdf.exe`,command line is `cmd.exe /c officetopdf.exe test.xlsx`.

**Comment by lauritsriple** [comment]
Maybe related to #33, #19. The solutions mentioned there seems to work for me running OfficeToPDF from Jenkins job (running as service)

**Comment by zssng** [comment]
Create deskstop folder still got `���� COM �๤���� CLSID Ϊ {00024500-0000-0000-C000-000000000046} �����ʧ�ܣ�ԭ���ǳ������´���: 80070520 ָ���ĵ�¼�Ự�����ڡ������ѱ���ֹ�� (�쳣���� HRESULT:0x80070520)��`

**Comment by lauritsriple** [comment]
Maybe something like [this](https://stackoverflow.com/questions/3477086/accessing-office-word-object-model-through-asp-net-results-in-failed-due-to-the). Except that one is for Word, so you would have to change every mention of word with excel.

**Comment by zssng** [comment]
Thank you, it works!😁

> Maybe something like [this](https://stackoverflow.com/questions/3477086/accessing-office-word-object-model-through-asp-net-results-in-failed-due-to-the). Except that one is for Word, so you would have to change every mention of word with excel.
