### ISSUE TITLE
Make it Chocolatey package

### ISSUE THREAD

**Issue by stasvlasov** [cognidox/OfficeToPDF#7]
Dear OfficeToPDF developers, thank you for this wonderful software! 
It would be nice if I can install it with:
````
 choco install officetopdf -y
````

**Comment by rje6459** [comment]
Since this hasn't gotten much attention, I've created a Chocolatey Package Request in their issue tracker:
https://github.com/chocolatey/chocolatey-package-requests/issues/522.

Right now, all that is needed is someone to become a maintainer for this package.

**Comment by robellegate** [comment]
A Chocolatey package has been published, so this issue can be closed.
https://chocolatey.org/packages/office-to-pdf
