### ISSUE TITLE
about the license

### ISSUE THREAD

**Issue by yxdragon** [cognidox/OfficeToPDF#70]
Hi, As ms office is a commercial software, So could OfficeToPdf be appache? And can I use OfficeToPdf anywhere?

**Comment by vittala** [comment]
OfficeToPDF is licensed under the Apache2 license. The MS Office licensing terms are completely separate because Office2PDF is not a derivative of MS Office. So, you can use officetopdf anywhere, but you may not be licensed to use MS office anywhere
