### ISSUE TITLE
excel file has more sheets has different orientation 

### ISSUE THREAD

**Issue by liugt34** [cognidox/OfficeToPDF#84]
excel file has more than one sheet , the first sheet orientation  is portrait, the second sheet is landscape
when it export as pdf ,it all portrait
the orientation default as the first sheet?

![image](https://user-images.githubusercontent.com/8056013/167987320-235e4e34-4d09-4f2d-83eb-6de689ed9b9b.png)

![image](https://user-images.githubusercontent.com/8056013/167987364-5a0d2f2a-1f34-4b5d-864c-564122ae91d6.png)

**Comment by liugt34** [comment]
change the paper orientation to solve this problem

**Comment by 17764591637** [comment]
怎么处理的呢 小哥哥 没找到可以转成横向的开关参数
